version: '3.8'

networks:
  prod:
    driver: bridge
  prod-db:
    driver: bridge
  jenkins:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - prod
      - jenkins
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/lib/letsencrypt:/etc/lib/letsencrypt:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      - ./nginx/conf.d/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - jenkins

  frontend:
    container_name: frontend
    image: frontend
    build: frontend
    networks:
      - prod
    expose:
      - 3001
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=3001
      - SERVER_FALLBACK_PAGE=./public/index.html

  backend:
    container_name: backend
    image: backend
    build: backend
    networks:
      - prod
      - prod-db
    expose:
      - 8081
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=8081
      - SPRING_PROFILE=prod
      - PROD_DB_URL=jdbc:mysql://mysql:3306/${PROD_DB_DATABASE}?useSSL=false
      - PROD_DB_USERNAME
      - PROD_DB_PASSWORD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - JWT_ACCESS_SECRET_KEY_BASE64
      - JWT_ACCESS_EXPIRATION_SECONDS
      - JWT_REFRESH_SECRET_KEY_BASE64
      - JWT_REFRESH_EXPIRATION_SECONDS
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_BUCKET
      - S3_REGION
      - S3_PUBLIC_ACCESS_DOMAIN
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - prod-db
    expose:
      - 3306
    environment:
      - TZ=Asia/Seoul
      - MYSQL_TCP_PORT=3306
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${PROD_DB_DATABASE}
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
    volumes:
      - ./db/mysql:/var/lib/mysql

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    networks:
      - jenkins
    expose:
      - 8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    group_add:
      - ${DOCKER_GROUP_ID:-998}
