version: '3.8'

networks:
  test:
    driver: bridge
  test-db:
    driver: bridge
  jenkins:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    networks:
      - prod
      - jenkins
      - test
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/lib/letsencrypt:/etc/lib/letsencrypt:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf:ro
      - ./nginx/conf.d/default.test.conf:/etc/nginx/conf.d/default.test.conf:ro
      - ./nginx/conf.d/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
    depends_on:
      - frontend
      - backend
      - jenkins
      - frontend-test
      - backend-test

  frontend-test:
    container_name: frontend-test
    image: frontend-test
    build: frontend
    networks:
      - test
    expose:
      - 3001
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=3001
      - SERVER_FALLBACK_PAGE=/public/index.html

  backend-test:
    container_name: backend-test
    image: backend-test
    build: backend
    networks:
      - test
      - test-db
    expose:
      - 8081
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILE=prod
      - SERVER_PORT=8081
      - ALLOWED_ORIGIN=${TEST_ALLOWED_ORIGIN}
      - PROD_DB_HOST=mysql-test:3307
      - PROD_DB_USERNAME=${TEST_DB_USERNAME}
      - PROD_DB_PASSWORD=${TEST_DB_PASSWORD}
      - PROD_DB_NAME=${TEST_DB_NAME}
      - PROD_DB_OPTIONS=?useSSL=false&allowPublicKeyRetrieval=true
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI=${TEST_GOOGLE_REDIRECT_URI}
      - JWT_ACCESS_SECRET_KEY_BASE64
      - JWT_ACCESS_EXPIRATION_SECONDS
      - JWT_REFRESH_SECRET_KEY_BASE64
      - JWT_REFRESH_EXPIRATION_SECONDS
      - S3_ACCESS_KEY_ID
      - S3_SECRET_ACCESS_KEY
      - S3_REGION
      - S3_ENDPOINT
      - S3_BUCKET
      - S3_PUBLIC_BASE_URL
    depends_on:
      - mysql-test

  mysql-test:
    container_name: mysql-test
    image: mysql:8.0
    networks:
      - test-db
    expose:
      - 3307
    environment:
      - LC_ALL=C.UTF-8
      - TZ=UTC
      - MYSQL_TCP_PORT=3307
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${TEST_DB_NAME}
      - MYSQL_USER=${TEST_DB_USERNAME}
      - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
    volumes:
      - /var/lib/mysql-test:/var/lib/mysql

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:jdk21
    networks:
      - jenkins
    expose:
      - 8080
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /usr/libexec/docker/cli-plugins/docker-compose:/usr/libexec/docker/cli-plugins/docker-compose:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    group_add:
      - ${DOCKER_GROUP_ID:-998}
