spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:{baseUrl}/api/v1/login/oauth2/redirect/{registrationId}}
            scope:
              - email
  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:80}

jwt:
  access-secret-key-base64: ${JWT_ACCESS_SECRET_KEY_BASE64:iAbBnFDrPJgglJr+yO0dC1qITxoCJcm1HB8ZiFWhtN19lWOdCaiPmvqXRTLmqe4cIdaT5X62swd/8lfp8rdw0Q==}
  access-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:86400}
  refresh-secret-key-base64: ${JWT_REFRESH_SECRET_KEY_BASE64:zxY3hKXBd6MPmmxha1rwte7GayIdjuzOTeD6nyuO7MockdamStat6G0nDF2T8EJP041sdz4eZxEPNJEGIXGmiQ==}
  refresh-expiration-seconds: ${JWT_REFRESH_EXPIRATION_SECONDS:8640000}

s3:
  access-key-id: ${S3_ACCESS_KEY_ID}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}
  bucket: ${S3_BUCKET}
  endpoint: ${S3_ENDPOINT:https://dcfbfd9f489ad8a785c3cdb81469e07d.r2.cloudflarestorage.com}
  public-access-domain: ${S3_PUBLIC_ACCESS_DOMAIN}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL:jdbc:h2:mem:S10P12C209}
    username: ${DEV_DB_USERNAME:sa}
    password: ${DEV_DB_PASSWORD:sa}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL:jdbc:mysql://localhost:3306/S10P12C209}
    username: ${LOCAL_DB_USERNAME:ssafy}
    password: ${LOCAL_DB_PASSWORD:ssafy}
  jpa:
    show-sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
