spring:
  datasource:
    url: jdbc:mysql://localhost:3306/S10P12C209
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
