server:
  port: 80

spring:
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:S10P12C209
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
