spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  web:
    resources:
      add-mappings: false

server:
  port: ${SERVER_PORT:80}

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_DB_URL:jdbc:h2:mem:S10P12C209}
    username: ${DEV_DB_USERNAME:sa}
    password: ${DEV_DB_PASSWORD:sa}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${LOCAL_DB_URL:jdbc:mysql://localhost:3306/S10P12C209}
    username: ${LOCAL_DB_USERNAME:ssafy}
    password: ${LOCAL_DB_PASSWORD:ssafy}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

---